version: "2"

volumes:
    sense-data:

services:
    mqtt:
        image: panuwitp/mosquitto-arm
        ports:
            - "1883:1883"

    influxdb:
        restart: always
        build: ./influxdb
        volumes:
            - "sense-data:/data"

    grafana:
        restart: always
        build: ./grafana
        ports:
            - "80"
        volumes:
            - "sense-data:/data"
        environment:
            - "GF_SERVER_HTTP_PORT=80"
            - "GF_PATHS_PROVISIONING=/usr/src/app/provisioning"
            - "GF_SESSION_PROVIDER=memory"

    telegraf:
        build: ./telegraf
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
